@hostname = localhost
@port = 4545
@contentType = application/json

POST  http://{{hostname}}:{{port}}/save HTTP/1.1
Content-Type: {{contentType}}

{
    "userId": 1,
    "quizId": 1, 
    "score": 5
}